version: 1

formatters:
  file_formatter:
    format: '{asctime}-{name}  -level:{levelname}-  -message:{message}-  -function:{funcName}-  -line:{lineno}'
    datefmt: '%Y-%m-%d %H:%M:%S'
    style: '{'
  console_formatter:
    (): logger_settings.CustomFormatter
    format: '{asctime}-{name}  -level:{levelname}-  -message:{message}-  -function:{funcName}-  -line:{lineno}'
    datefmt: '%Y-%m-%d %H:%M:%S'
    style: '{'
handlers:
  console_handler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: console_formatter
  file_handler_errors:
    (): logger_settings.CustomHandler
    level: ERROR
    filename: 'error'
    maxBytes: 10485760 # 10MB
    backupCount: 10
    encoding: utf-8
    formatter: file_formatter
    mode: a
  file_handler_debug:
    (): logger_settings.CustomHandler
    level: DEBUG
    filename: 'debug'
    maxBytes: 10485760 # 10MB
    backupCount: 10
    encoding: utf-8
    formatter: file_formatter
    filters: [debug_filter]
    mode: a
filters:
  debug_filter:
    (): logger_settings.CustomFilter
loggers:
  RKSOK_Logger:
    level: DEBUG
    handlers: [ console_handler, file_handler_errors, file_handler_debug ]
    propagate: True
disable_existing_loggers: False





























